// Served as a Route Handler, not a public/ static file: Firebase App
// Hosting applies its own long default Cache-Control to static public/
// assets, bypassing next.config.ts's headers() rule entirely for that
// path (confirmed via curl — the /sw.js response carried max-age=2678400
// despite the config). A service worker script MUST be re-checked
// promptly on every deploy or updates (including crash fixes) can take
// up to that long to reach already-installed clients. Setting the header
// directly on the Response here, from Next's own route handling instead
// of the static-file layer, is the only way that's actually honored.

const SW_SOURCE = `
// Oltinde service worker — installable + offline browsing of recently-viewed
// public pages. Hand-written (no Workbox/next-pwa/serwist) so the caching
// rules stay simple and auditable: nothing beyond what's needed for
// "browse pages you've already visited with no signal."
//
// Bump CACHE_VERSION on any change to the caching rules below so stale
// caches from a previous version get cleaned up on activate.
const CACHE_VERSION = 'v2';
const APP_SHELL_CACHE = \`oltinde-shell-\${CACHE_VERSION}\`;
const RUNTIME_CACHE = \`oltinde-runtime-\${CACHE_VERSION}\`;
const STATIC_CACHE = \`oltinde-static-\${CACHE_VERSION}\`;
const ALL_CACHES = [APP_SHELL_CACHE, RUNTIME_CACHE, STATIC_CACHE];

const OFFLINE_URL = '/offline';
const APP_SHELL_URLS = [
  '/',
  OFFLINE_URL,
  '/manifest.webmanifest',
  '/icons/icon-192.png',
  '/icons/icon-512.png',
];

// Auth-gated routes are checked client-side only (no server-side cookie
// check on these pages), so a cached shell could flash stale/wrong UI
// before the client redirect fires. Never cache these — always network.
const NEVER_CACHE_PREFIXES = [
  '/admin',
  '/dashboard',
  '/signin',
  '/signup',
  '/reset-password',
  '/profile',
  '/notifications',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(APP_SHELL_CACHE).then((cache) => cache.addAll(APP_SHELL_URLS))
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => !ALL_CACHES.includes(key))
          .map((key) => caches.delete(key))
      )
    )
  );
  self.clients.claim();
});

function isNeverCachePath(pathname) {
  return NEVER_CACHE_PREFIXES.some((prefix) => pathname.startsWith(prefix));
}

// Deliberately does NOT include /_next/static/ here. Those filenames are
// content-hashed, so a naive cache-first strategy looks safe — but on a
// new deploy the referenced webpack runtime chunk and the vendor/app
// chunks it resolves can shift out of sync with what's still sitting in
// this cache (which never expires or revalidates), causing a hard crash:
// "Cannot read properties of undefined (reading 'call')" when the stale
// runtime can't find a module it expects. The browser's own HTTP cache
// already caches these correctly (unique URL per build, long
// immutable max-age) — this SW doesn't need to duplicate that, and doing
// so is what caused the crash. Only /icons/ stays cache-first: those are
// regenerated by hand, not per-deploy, and CACHE_VERSION gets bumped when
// they change.
function isStaticAsset(pathname) {
  return pathname.startsWith('/icons/');
}

async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok) cache.put(request, response.clone());
  return response;
}

async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const networkPromise = fetch(request)
    .then((response) => {
      if (response.ok) cache.put(request, response.clone());
      return response;
    })
    .catch(() => undefined);

  if (cached) {
    // Update the cache in the background; don't make the caller wait for it.
    networkPromise.catch(() => {});
    return cached;
  }

  const networkResponse = await networkPromise;
  if (networkResponse) return networkResponse;

  if (request.mode === 'navigate') {
    const offline = await caches.match(OFFLINE_URL);
    if (offline) return offline;
  }
  return Response.error();
}

self.addEventListener('fetch', (event) => {
  const { request } = event;

  // Only ever intercept our own GET requests. All Server Actions are POST —
  // never touch those, or a mutation could be swallowed or double-fired.
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (isNeverCachePath(url.pathname)) return; // let it hit the network untouched

  // Built JS/CSS chunks: leave entirely to the browser's own HTTP cache
  // (see the note on isStaticAsset above) — don't let this SW touch them
  // at all, not even via the runtime stale-while-revalidate fallback below.
  if (url.pathname.startsWith('/_next/static/')) return;

  if (isStaticAsset(url.pathname)) {
    event.respondWith(cacheFirst(request, STATIC_CACHE));
    return;
  }

  event.respondWith(staleWhileRevalidate(request, RUNTIME_CACHE));
});

// Push notifications (Firebase Cloud Messaging). The server sends a
// data-only payload (no "notification" key) so the message never displays
// automatically — this handler is the single place that decides what the
// OS notification looks like and where a click routes to.
self.addEventListener('push', (event) => {
  if (!event.data) return;
  let payload;
  try {
    payload = event.data.json();
  } catch {
    return;
  }
  const data = payload.data || payload;
  const title = data.title || 'Oltinde';
  event.waitUntil(
    self.registration.showNotification(title, {
      body: data.body,
      icon: '/icons/icon-192.png',
      badge: '/icons/icon-192.png',
      data: { link: data.link || '/' },
    })
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const link = event.notification.data?.link || '/';
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url.includes(link) && 'focus' in client) return client.focus();
      }
      if (self.clients.openWindow) return self.clients.openWindow(link);
    })
  );
});
`;

export async function GET() {
  return new Response(SW_SOURCE, {
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Cache-Control': 'no-cache',
      'Service-Worker-Allowed': '/',
    },
  });
}
